site_name: Practical Solution Delivery
theme:
  name: material
Nav:
-Home: index.md
-Design: design.md
-Process : process.md 
-Assessment : assessment.md
-Diagrams :  diagrams.md
-Communications : communications.md
-Duties: duties.md
-Adrs: adrs.md
-Cloud: cloudArch.md
-Influence: influence.md
-Stakeholders: stakeholders.md
-ETA: eta.md