site_name: Modern Solution Delivery for Products and Services
theme:
  name: material
  features:
    - navigation.instant
    - content.code.copy
    - search.suggest
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: teal
    - scheme: slate
      primary: blue
      accent: cyan
markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - def_list
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
Nav:
-Home: index.md
-Intake: intake.md
-Design: design.md
-Process : process.md 
-Assessment : assessment.md
-Diagrams :  diagrams.md
-Communications : communications.md
-Duties: duties.md
-Adrs: adrs.md
-Cloud: cloudArch.md
-Influence: influence.md
-Stakeholders: stakeholders.md
-ETA: eta.md